apiVersion: v1
kind: Pod
metadata:
  name: loadgen
  namespace: demo
  labels:
    app: loadgen
spec:
  containers:
  - name: loadgen
    image: busybox
    command: ["/bin/sh"]
    args:
    - "-c"
    - "while true; do wget -q -O- http://podinfo:9898 >/dev/null 2>&1; sleep 0.2; done"
  restartPolicy: Always
